version: '3.9'

services:
  frontend:
    build: 
      context: . 
      dockerfile: frontend.Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./word-wolf-frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
    

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./word-wolf-backend:/app/backend